spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-onboarding
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
#This is not PRD , then consider you'll put it in secrets in e.g the K8s!
jwt:
  secret: deld____###gfhjkljhgfhjkljhgfhjklkjhgfhjkl;kjhgjkljhgAhjklkjhghjklAhjkljhgjkl43243243ladla
